#!/bin/sh

cmd=$1
shift
case "$cmd" in
  bootstrap)
    sh ./autogen.sh
    ;;
  configure)
    ./configure $@
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0
